# Generated by Django 4.2.2 on 2023-07-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True)),
                ('longtude', models.FloatField(blank=True)),
                ('height', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.TextField(blank=True)),
                ('summer', models.TextField(blank=True)),
                ('autumn', models.TextField(blank=True)),
                ('spring', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('third_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beutytitle', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('other_titles', models.TextField(blank=True)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('new', 'новый'), ('pending', 'на рассмотрении'), ('accepted', 'успешно'), ('rejected', 'не принята')], default='new', max_length=10)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coord')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval_images')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users')),
            ],
        ),
    ]
